---
# Install apt font packages
- name: Install fonts packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: no
  loop: "{{ packages.fonts }}"

# Install Nerd font
- name: Install Jetbrains Nerd Font
  block:
    - name: Create Directory
      ansible.builtin.file:
        path: "/home/{{ user }}/.fonts/JetBrainsMonoNerd"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
    - name: Download
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
        dest: "/home/{{ user }}/.fonts/JetBrainsMonoNerd"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Font cache update
      action: command fc-cache -fv
