---
# Installs [Starship](https://starship.rs/) prompt
- name: Check if Starship is installed
  ansible.builtin.stat:
    path: /home/{{ user }}/.config/starship.toml
  register: starship

- name: Install
  when: not starship.stat.exists
  ansible.builtin.command: "{{ linuxbrew_executable }} install starship"
  environment: 
    HOME: "/home/{{ user }}"
  args:
    executable: /bin/bash

# Installing [Fisher](https://github.com/jorgebucaran/fisher)
- name: Install Fisher
  ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
  environment:
    HOME:  "/home/{{ user }}"
  args:
    executable: /bin/fish
